### ISSUE TITLE
IO pins on user_analog_project_wrapper

### ISSUE THREAD

**Issue by adithyasunil26** [efabless/caravel_user_project_analog#15]
It would be great to know the structure of the `gpio_analog`, `gpio_noesd` and `io_analog` pins on the pad-frame. Knowing the load resistance or capacitance present would help in designing efficient measurement circuits and buffers for analog designs.

**Comment by RTimothyEdwards** [comment]
We need additional documentation, as some of the specs for the I/O cells in particular are in SkyWater documentation that did not get into the public repository.
![caravan_pads](https://user-images.githubusercontent.com/12645599/192624962-c5369e1c-b123-4c73-8d5c-6536df73d71b.png)
This diagram explains the data connections to the pads on the caravan chip.  For the eleven pads across the top, there is a straight-through wire from the pad to the core, with no ESD protection.  Those are the `io_analog` pins.  The GPIO pads are more flexible;  they have digital input and output buffers, but those can both be turned off by configuration, and analog signals can be connected via `gpio_noesd` (straight wire through from the pad) or `gpio_analog` (wire to the pad in series with a 150 ohm resistor).  Both of these analog connections have ESD protection diodes---the "noesd" in the name refers to the fact that there is no additional machine-model (MM) ESD protection.  Do not use `gpio_noesd` unless your circuit cannot tolerate the 150 ohm series resistance (and if you do use it, be aware that your chip will be considerably more ESD-sensitive).
