### ISSUE TITLE
About the consistency problem in precheck

### ISSUE THREAD

**Issue by Elon-J** [efabless/caravel_user_project_analog#27]
When I run the precheck for our design, I meet the consistency problem; how can I solve it? Attach the precheck result, Thank you!
![image](https://user-images.githubusercontent.com/88715865/183233261-c1853f5c-f294-4a10-85b8-23abde3ade06.png)

**Comment by mithro** [comment]
Can you provide a reproducible way to cause this error?

**Comment by mithro** [comment]
FYI - @jeffdi

**Comment by msaligane** [comment]
@Elon-J can you provide a testcase

**Comment by mithro** [comment]
Does https://github.com/efabless/mpw_precheck/pull/138 fix the issue?

**Comment by RTimothyEdwards** [comment]
@mithro :  Yes, it does, and it has been tested and verified.  But it has not been deployed to the Efabless platform.  Jeff made a request to have it deployed two days ago, but it hasn't happened yet.  I was just promised that it would be done tomorrow morning.

**Comment by Elon-J** [comment]
@mithro, sorry for my lateness; I have constructed a test circuit, and the pre-check work well.

<img width="1352" alt="image" src="https://user-images.githubusercontent.com/88715865/188366700-0e9340c3-8993-4b97-9c19-8dfef93d4dfb.png">
