### ISSUE TITLE
Analog flow is completely broken

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/caravel_user_project_analog#31]
All of the .mag files in the magic/ directory have `tech $PDK` as the second line, which is not handled by magic and completely breaks the design flow and causes everything to fail.

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  This error appears to come from commit `014204425607cc32b9d26b35a2963a7632ee35ca` with your name on it.  Can you explain this commit??

**Comment by marwaneltoukhy** [comment]
@RTimothyEdwards This was to change the pdk name to be a variable, so `sky130A` changed to `PDK` environment variable, `PDK` should be exported same as how we export `PDK_ROOT`, to either `sky130A` or `sky130B`

**Comment by RTimothyEdwards** [comment]
@marwaneltoukhy :  But you can't do that!  The `.mag` file is a specific, documented format, and variables are not part of that format.  By putting a variable in the file, you break the file format and magic isn't going to accept that file, breaking magic for anybody who uses it on any of those files.  There is a good reason that the field isn't a variable, which is that layouts are all very specific to processes and process variants.  You would not, generally speaking, want the same layout for a different variant.  At any rate, there is _already_ a known way of moving a file from one technology to another in magic, which is to use the "load -force" option.

If you wish to specify that a layout could be compatible with multiple variants, I would at least require that the format have specific control over which variants are allowed, but allowing _any_ variant whatsoever is just wrong, wrong, wrong.  I would be happy to discuss making some extension to magic to allow a limited selection of compatible technologies, such as, perhaps, "tech sky130A|sky130B" or "tech (sky130A sky130B)" or somesuch.

**Comment by RTimothyEdwards** [comment]
See pull request #34

**Comment by DavidRLindley** [comment]
The PR is still open yet this evidently isn't still a problem.  I'm closing
